stages:
  - fetch_secret

fetch_secret:
  stage: fetch_secret
  only:
    - main
  image: 
    name: amazon/aws-cli:2.x
    entrypoint: [""]
  before_script:
    - apt-get update -y
    - apt-get install -y jq
  script:
    - |
      ROLE_ARN="arn:aws:iam::<834755374850>:role/interview-bot"
      RESULT=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name "GitLabCI")
      export AWS_ACCESS_KEY_ID=$(echo $RESULT | jq -r '.Credentials.AccessKeyId')
      export AWS_SECRET_ACCESS_KEY=$(echo $RESULT | jq -r '.Credentials.SecretAccessKey')
      export AWS_SESSION_TOKEN=$(echo $RESULT | jq -r '.Credentials.SessionToken')
      
      SECRET_ARN="arn:aws:secretsmanager:us-west-2:<834755374850>:secret:extend-interview/Asharib121"
      SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $SECRET_ARN --query SecretString --output text)
      echo "SECRET_VALUE=$SECRET_VALUE" > secret.txt
  artifacts:
    paths:
      - secret.txt
